# Generated by Django 4.0.3 on 2022-04-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=20)),
                ('cardNo', models.IntegerField(null=True)),
                ('expiryDate', models.DateField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('streetNo', models.IntegerField()),
                ('streetName', models.CharField(max_length=20)),
                ('postCode', models.CharField(max_length=7)),
                ('landline', models.CharField(max_length=11)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ageRating', models.CharField(max_length=2)),
                ('duration', models.TimeField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('noSeats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField()),
                ('paymentMethod', models.CharField(max_length=6)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.account')),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.statement')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=7)),
                ('cost', models.IntegerField()),
                ('seatRef', models.CharField(max_length=3)),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.showing')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.club'),
        ),
    ]
