# Generated by Django 4.0.3 on 2022-03-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubID', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('streetNo', models.IntegerField(default=0)),
                ('streetName', models.CharField(max_length=200)),
                ('postCode', models.CharField(max_length=200)),
                ('landline', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(verbose_name='date of birth')),
            ],
        ),
    ]
