# Generated by Django 4.0.3 on 2022-03-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0002_alter_clubreg_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubreg',
            name='dob',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.IntegerField(default=0)),
                ('cardNo', models.IntegerField(default=0)),
                ('expiryDate', models.DateField(verbose_name='Expiry date')),
                ('discount', models.FloatField(default=0.0)),
                ('clubID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.clubreg')),
            ],
        ),
    ]
