# Generated by Django 4.0.3 on 2022-03-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0003_alter_clubreg_dob_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmID', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('ageRating', models.CharField(max_length=100)),
                ('duration', models.DateTimeField(verbose_name='Duration')),
                ('trailerDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenID', models.IntegerField(default=0)),
                ('screenNo', models.IntegerField(default=0)),
                ('noSeats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showingID', models.IntegerField(default=0)),
                ('dateTime', models.DateTimeField(verbose_name='Showing date/time')),
                ('filmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.film')),
                ('screenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.screen')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.IntegerField(default=0)),
                ('purchaseDateTime', models.DateTimeField(verbose_name='Purchase date/time')),
                ('noTickets', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('paymentType', models.CharField(max_length=100)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketID', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=100)),
                ('cost', models.FloatField(default=0.0)),
                ('showingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.showing')),
            ],
        ),
        migrations.CreateModel(
            name='EndOfMonthStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statementID', models.IntegerField(default=0)),
                ('month', models.DateField(verbose_name='Month')),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWEFlixApp.account')),
            ],
        ),
    ]
